services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    volumes:
      - /opt/appdata/openwebui/models:/root/.ollama
    networks:
      - ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    # environment:
    #   - HSA_OVERRIDE_GFX_VERSION=gfx1102 # Adjust for your AMD GPU

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    volumes:
      - /opt/appdata/openwebui/openwebui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    restart: unless-stopped
    networks:
      - proxy
      - ollama
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.entrypoints=https"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"
      - "traefik.http.services.${TRAEFIK_ROUTER_NAME}.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
  ollama: