services:
  troop711:
    image: ghcr.io/xcraftman52/troop711:latest@sha256:fa63b76bb78e2d32b2a7b700fe705166f8e01bb43b81d374a23ec8b5bc71c1df
    container_name: troop711
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.troop711.rule=Host(`$TROOP_DOMAIN_NAME`)"
      - "traefik.http.routers.troop711.entrypoints=https"
      - "traefik.http.routers.troop711.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.troop711.loadBalancer.server.port=3000"

networks:
  proxy:
    external: true