services:
    webberlights:
      networks:
      - proxy
      security_opt:
      - no-new-privileges:true
      restart: always
      image: ghcr.io/webber-lights/webberlights.com:d31b459
      container_name: webberlights
      environment:
          - FPP_URL
          - NEXT_PUBLIC_BANNER_ENABLED
          - NEXT_PUBLIC_BANNER_TEXT
          - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.webberlights.rule=Host(`$WEBBER_LIGHTS_DOMAIN_NAME`)"
        - "traefik.http.routers.webberlights.entrypoints=https"
        - "traefik.http.routers.webberlights.tls.certresolver=dns-cloudflare"

        - "traefik.http.routers.webberlights-www.rule=Host(`www.$WEBBER_LIGHTS_DOMAIN_NAME`)"
        - "traefik.http.routers.webberlights-www.entrypoints=https"
        - "traefik.http.routers.webberlights-www.tls.certresolver=dns-cloudflare"
        - "traefik.http.routers.webberlights-www.middlewares=redirect-www-to-non-www@docker"
networks:
  proxy:
    external: true
