---
- name: Deploy Docker Service
  hosts: "{{ target_host }}"
  become: true

  vars:
    service_path: "/opt/iac/docker/{{ service }}"

  tasks:
    - name: Login to GHCR
      community.docker.docker_login:
        registry_url: ghcr.io
        username: "{{ ghcr_username }}"
        password: "{{ ghcr_token }}"

    - name: Update repository
      ansible.builtin.git:
        repo: git@github.com:XCraftMan52/iac.git
        dest: /opt/iac
        version: main
        update: true
        key_file: /home/xcraftman52/.ssh/id_ed25519

    - name: Restart Docker Compose service
      community.docker.docker_compose_v2:
        project_src: "{{ service_path }}"
        pull: always
        state: present
        remove_orphans: true