services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    networks:
    - proxy
    security_opt:
    - no-new-privileges:true
    restart: always
    volumes:
      - ./data/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.entrypoints=https"
      - "traefik.http.routers.uptime-kuma.rule=Host(`$DOMAINNAME_UPTIME`)"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"

networks:
  proxy:
    external: true